// Start pnpm dev, then run pnpm test:ui. Uses isolated browser storage; no backend.
import { chromium, expect } from "@playwright/test"
import { mkdir } from "node:fs/promises"

const base = process.env.SCRAWL_TEST_URL ?? "http://localhost:3000"
const browser = await chromium.launch()
const errors = []
async function fixture(options = {}) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, ...options })
  const page = await context.newPage()
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto(base)
  await page.waitForFunction(() => !!window.scrawl)
  return { context, page }
}

try {
  const { context, page } = await fixture()
  const font = page.getByRole("button", { name: "About Font", exact: true })
  const tooltip = page.getByRole("tooltip")
  await font.hover()
  // A brief pass must not flash help; intentional hover must reveal it.
  await page.waitForTimeout(250)
  await expect(tooltip).toHaveCount(0)
  await expect(tooltip).toHaveText("Saved per drawing; reused for new drawings.")
  await tooltip.hover()
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)

  await page.keyboard.press("Tab")
  await font.focus()
  await expect(font).toHaveAccessibleDescription("Saved per drawing; reused for new drawings.")
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)
  await expect(font).toBeFocused()
  await page.keyboard.press("Enter")
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Tab")
  await expect(tooltip).toHaveCount(0)

  await page.getByRole("button", { name: "Components", exact: true }).click()
  await expect(page.getByRole("textbox", { name: "Search components" })).toBeFocused()
  await page.getByRole("button", { name: "About Components" }).click()
  await expect(tooltip).toHaveText("Drag an item onto the canvas, or select it and click to place.")
  await page.getByRole("textbox", { name: "Search components" }).focus()
  await page.keyboard.press("Escape")

  await page.evaluate(() => window.scrawl.addComponent("navbar", { x: 200, y: 200 }))
  await expect(page.getByRole("textbox", { name: "Links", exact: true })).toHaveAccessibleDescription("Separate items with commas.")
  await page.getByRole("button", { name: "About Links", exact: true }).click()
  await expect(tooltip).toHaveText("Separate items with commas.")
  await page.keyboard.press("Escape")
  await page.evaluate(() => window.scrawl.addText("Hello", { x: 200, y: 400 }))
  await expect(page.getByRole("textbox", { name: "Font size", exact: true })).toBeVisible()
  await page.evaluate(() => window.scrawl.select([]))

  const searchTrigger = page.getByRole("button", { name: "Search ⌘K" })
  await searchTrigger.click()
  const search = page.getByRole("textbox", { name: "Search commands, layers, components, blocks, and icons" })
  const dialog = page.getByRole("dialog", { name: "Search Scrawl" })
  await expect(search).toBeFocused()
  await expect(page.locator("[inert]")).toHaveCount(1)
  await page.keyboard.press("Shift+Tab")
  expect(await dialog.evaluate((el) => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press("Tab")
  await expect(search).toBeFocused()
  await page.getByRole("button", { name: "About Help" }).focus()
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)
  await expect(dialog).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(searchTrigger).toBeFocused()

  // A command that opens another dialog must not immediately close it again.
  await searchTrigger.click()
  await search.fill("Keyboard shortcuts")
  await page.keyboard.press("Enter")
  await expect(page.getByRole("dialog", { name: "Keyboard", exact: true })).toBeVisible()
  const close = page.getByRole("button", { name: "Close keyboard shortcuts" })
  await expect(close).toBeFocused()
  await page.keyboard.press("Shift+Tab")
  await expect(page.getByRole("region", { name: "Keyboard shortcuts" })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(close).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)

  await page.goto(`${base}/connect`)
  await expect(page.getByRole("heading", { name: "Connect your agent" })).toBeVisible()
  const config = page.locator("details").filter({ has: page.getByText("Manual Codex config", { exact: true }) })
  await expect(config.locator("pre")).not.toBeVisible()
  await config.locator("summary").focus()
  await page.keyboard.press("Enter")
  await expect(config.locator("pre")).toBeVisible()
  await expect(page.getByText("Agent canvases are saved online. Local drawings stay in this browser.")).toBeVisible()
  await context.close()

  const files = await fixture()
  const fileMenu = files.page.getByRole("button", { name: "scrawl", exact: true })
  async function openRecents() {
    await expect(files.page.getByRole("menu")).toHaveCount(0)
    await fileMenu.click()
    await files.page.getByRole("menuitem", { name: "Open recent", exact: true }).press("ArrowRight")
    await expect(files.page.getByRole("menu", { name: "Open recent", exact: true })).toHaveCSS("opacity", "1")
  }
  async function renameFile(name) {
    await files.page.evaluate(() => {
      window.scrawl.addText("List test", { x: 200, y: 200 })
      window.scrawl.select([])
    })
    await files.page.getByRole("button", { name: "untitled scribbles", exact: true }).click()
    await files.page.getByRole("textbox", { name: "file name", exact: true }).fill(name)
    await files.page.getByRole("textbox", { name: "file name", exact: true }).press("Enter")
  }
  const draftName = "A very long drawing name that should truncate without moving the check"
  await renameFile(draftName)
  await fileMenu.click()
  await files.page.getByRole("menuitem", { name: "New file", exact: true }).click()
  await renameFile("Current drawing")
  await openRecents()
  const current = files.page.getByRole("menuitem", { name: /Current drawing/ })
  const draft = files.page.getByRole("menuitem", { name: new RegExp(draftName) })
  const trash = files.page.getByRole("button", { name: `delete ${draftName}`, exact: true })
  const mark = current.locator('[data-slot="selection-indicator"]')
  await expect(current).toHaveAttribute("aria-current", "true")
  await expect(mark).toBeVisible()
  await expect(draft.locator('[data-slot="selection-indicator"]')).not.toBeVisible()
  await draft.hover()
  await expect(trash).toHaveCSS("opacity", "1")
  const [currentLabel, draftLabel, rowBox, markBox, trashBox] = await Promise.all([
    current.locator("span").first().boundingBox(), draft.locator("span").first().boundingBox(),
    current.boundingBox(), mark.boundingBox(), trash.boundingBox(),
  ])
  expect(currentLabel.x).toBe(draftLabel.x)
  expect(rowBox.x + rowBox.width - markBox.x - markBox.width).toBeCloseTo(8, 0)
  expect(trashBox.x + trashBox.width).toBeLessThan(markBox.x)
  expect(draftLabel.x + draftLabel.width).toBeLessThan(trashBox.x)
  await mkdir("test-results/list-selection", { recursive: true })
  await files.page.screenshot({ path: "test-results/list-selection/files.png" })

  await draft.click()
  await openRecents()
  await expect(draft).toHaveAttribute("aria-current", "true")
  expect((await draft.locator("span").first().boundingBox()).x).toBe((await current.locator("span").first().boundingBox()).x)
  await expect(current.locator('[data-slot="selection-indicator"]')).not.toBeVisible()
  await current.click()
  await openRecents()

  await trash.click()
  const confirmation = files.page.getByRole("alertdialog", { name: "Delete drawing?" })
  const cancel = confirmation.getByRole("button", { name: "Cancel", exact: true })
  const remove = confirmation.getByRole("button", { name: "Delete", exact: true })
  await expect(confirmation).toContainText(draftName)
  await expect(confirmation).toContainText("This cannot be undone.")
  await expect(cancel).toBeFocused()
  await expect(files.page.getByRole("menu")).toHaveCount(0)
  await files.page.screenshot({ path: "test-results/list-selection/delete.png" })
  await files.page.keyboard.press("Shift+Tab")
  await expect(remove).toBeFocused()
  await files.page.keyboard.press("Tab")
  await expect(cancel).toBeFocused()
  await files.page.keyboard.press("r")
  await files.page.keyboard.press("Escape")
  await expect(confirmation).toHaveCount(0)
  await expect(fileMenu).toBeFocused()
  await expect(files.page.getByRole("button", { name: "Select", exact: true })).toHaveAttribute("aria-pressed", "true")
  await openRecents()
  await expect(draft).toBeVisible()
  await trash.click()
  // Enter on the initial focus cancels instead of deleting.
  await expect(cancel).toBeFocused()
  await files.page.keyboard.press("Enter")
  await expect(confirmation).toHaveCount(0)
  await openRecents()
  await expect(draft).toBeVisible()
  await trash.click()
  await remove.click()
  await expect(confirmation).toHaveCount(0)
  await openRecents()
  await expect(draft).toHaveCount(0)
  await expect(current).toHaveAttribute("aria-current", "true")
  await files.page.keyboard.press("Escape")
  await files.page.keyboard.press("Escape")

  const palette = files.page.getByRole("button", { name: /^Palette —/ })
  await palette.click()
  const selectedInk = files.page.getByRole("menuitem", { name: "Internet blue", exact: true })
  await expect(files.page.getByRole("menu").filter({ has: selectedInk })).toHaveCSS("opacity", "1")
  const inkMark = selectedInk.locator('[data-slot="selection-indicator"]')
  const [inkBox, inkMarkBox] = await Promise.all([selectedInk.boundingBox(), inkMark.boundingBox()])
  expect(inkBox.x + inkBox.width - inkMarkBox.x - inkMarkBox.width).toBeCloseTo(8, 0)
  await files.page.screenshot({ path: "test-results/list-selection/palette.png" })
  await files.page.keyboard.press("Escape")
  await files.page.evaluate(() => window.scrawl.addComponent("button", { x: 200, y: 200 }))
  const select = files.page.locator('[data-slot="select-trigger"]').first()
  await select.click()
  const selectedOption = files.page.getByRole("option", { selected: true })
  const optionMark = selectedOption.locator('[data-slot="selection-indicator"]')
  await expect(optionMark).toBeVisible()
  const [optionBox, optionMarkBox] = await Promise.all([selectedOption.boundingBox(), optionMark.boundingBox()])
  expect(optionBox.x + optionBox.width - optionMarkBox.x - optionMarkBox.width).toBeCloseTo(8, 0)
  await files.context.close()

  const touch = await fixture({ hasTouch: true, reducedMotion: "reduce", viewport: { width: 390, height: 844 } })
  await touch.page.getByRole("button", { name: "About Font", exact: true }).tap()
  await expect(touch.page.getByRole("tooltip")).toHaveText("Saved per drawing; reused for new drawings.")
  expect(await touch.page.getByRole("tooltip").evaluate((el) => getComputedStyle(el).transitionProperty)).toBe("none")
  expect(await touch.page.getByRole("tooltip").evaluate((el) => getComputedStyle(el).transform)).toBe("none")
  const bounds = await touch.page.getByRole("tooltip").boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  await touch.page.getByRole("heading", { name: "Page", exact: true }).tap()
  await expect(touch.page.getByRole("tooltip")).toHaveCount(0)
  await touch.context.close()
  expect(errors).toEqual([])
  console.log("UI helper checks passed: delayed/hoverable help, keyboard, touch, reduced motion, field descriptions, modal focus, setup disclosure.")
} finally {
  await browser.close()
}
