// pnpm dev, then node scripts/ui/spacing-browser.mjs
import { chromium, expect } from "@playwright/test"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on("pageerror", (e) => errors.push(e.message))
try {
  await page.goto(process.env.SCRAWL_TEST_URL ?? "http://localhost:3000")
  await page.waitForFunction(() => !!window.scrawl)
  await page.evaluate(() => {
    const nodes = [0, 160, 320].map((x, i) => ({ id: `spacing-${i}`, type: "shape", shape: "rect", x: x + 300, y: 250, w: 100, h: 100, fill: "light", seed: i + 1 }))
    window.scrawl.add(nodes)
    window.scrawl.select(nodes.map((n) => n.id))
  })
  const positions = () => page.evaluate(() => [0, 1, 2].map((i) => { const n = window.scrawl.doc().nodes[`spacing-${i}`]; return [n.x, n.w] }))
  const gap = page.getByRole("button", { name: "Horizontal gap 60 pixels", exact: true }).first()
  await expect(gap).toBeVisible()
  const box = await gap.boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.screenshot({ path: "/tmp/scrawl-spacing-before.png" })
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 20, box.y + box.height / 2, { steps: 5 })
  await expect(page.getByRole("status")).toHaveText("80 px")
  await page.mouse.up()
  expect(await positions()).toEqual([[300, 100], [480, 100], [660, 100]])
  await page.keyboard.press("Meta+z")
  expect(await positions()).toEqual([[300, 100], [460, 100], [620, 100]])
  const field = page.getByRole("textbox", { name: "Horizontal gap", exact: true })
  await field.click()
  await field.press("Meta+a")
  await field.pressSequentially("24")
  await field.press("Enter")
  expect(await positions()).toEqual([[300, 100], [424, 100], [548, 100]])
  const next = page.getByRole("button", { name: "Horizontal gap 24 pixels", exact: true }).first()
  const nb = await next.boundingBox()
  await page.mouse.move(nb.x + 14, nb.y + 14)
  await page.mouse.down()
  await page.mouse.move(nb.x + 54, nb.y + 14, { steps: 4 })
  await page.keyboard.press("Escape")
  await page.mouse.up()
  expect(await positions()).toEqual([[300, 100], [424, 100], [548, 100]])
  const ring = page.getByRole("button", { name: "Reorder spacing-0; click to mark for resizing", exact: true })
  const rb = await ring.boundingBox()
  await page.mouse.move(rb.x + 14, rb.y + 14)
  await page.mouse.down()
  await page.mouse.move(rb.x + 194, rb.y + 14, { steps: 8 })
  await page.mouse.up()
  expect(await positions()).toEqual([[424, 100], [300, 100], [548, 100]])
  await ring.click()
  const resize = page.getByRole("button", { name: "Resize marked width, keep gaps", exact: true })
  const zb = await resize.boundingBox()
  await page.mouse.move(zb.x + 10, zb.y + 10)
  await page.mouse.down()
  await page.mouse.move(zb.x + 30, zb.y + 10, { steps: 5 })
  await page.mouse.up()
  expect(await positions()).toEqual([[424, 120], [300, 100], [568, 100]])
  await page.screenshot({ path: "/tmp/scrawl-spacing-after.png" })
  await page.evaluate(() => {
    window.scrawl.remove(["spacing-0", "spacing-1", "spacing-2"])
    const nodes = [0, 1, 2, 3, 4, 5].map((i) => ({ id: `grid-${i}`, type: "shape", shape: "rect", x: 300 + (i % 3) * 160 + (i === 2 ? 12 : 0), y: 200 + Math.floor(i / 3) * 170, w: 100, h: 100, fill: "light", seed: i + 1 }))
    window.scrawl.add(nodes)
    window.scrawl.select(nodes.map((n) => n.id))
  })
  await page.getByRole("button", { name: "Tidy up", exact: true }).last().click()
  const vertical = page.getByRole("button", { name: "Vertical gap 60 pixels", exact: true }).first()
  await expect(vertical).toBeVisible()
  await vertical.focus()
  await page.keyboard.press("Shift+ArrowDown")
  expect(await page.evaluate(() => [3, 4, 5].map((i) => window.scrawl.doc().nodes[`grid-${i}`].y))).toEqual([370, 370, 370])
  const gridRing = page.getByRole("button", { name: "Reorder grid-0; click to mark for resizing", exact: true })
  await gridRing.focus()
  await page.keyboard.press("ArrowRight")
  expect(await page.evaluate(() => window.scrawl.doc().nodes["grid-0"].x)).toBe(460)
  await page.screenshot({ path: "/tmp/scrawl-spacing-grid.png" })
  expect(errors).toEqual([])
  console.log("Spacing browser checks passed: hover, drag, exact gap, undo, Escape, reorder, marked resize")
} finally { await browser.close() }
