// Generates lib/sketch/doodle.ts from a .scrawl file of freehand strokes.
// Run: node scripts/gen-doodle.mjs <file.scrawl.json>
//
// The empty canvas shows a drawing Pablo made in scrawl itself. Baking it into
// path data rather than shipping the .scrawl and re-running rough.js on every
// mount keeps the file small (points get simplified first) and the graphic
// identical between reloads — it's a printed illustration now, not a sketch
// the app re-draws.

import { readFileSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import rough from "roughjs"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const src = process.argv[2]
if (!src) {
  console.error("usage: node scripts/gen-doodle.mjs <file.scrawl.json>")
  process.exit(1)
}

const doc = JSON.parse(readFileSync(src, "utf8"))
const strokes = doc.order
  .map((id) => doc.nodes[id])
  .filter((n) => n && n.type === "draw" && n.points?.length)

if (!strokes.length) {
  console.error("no freehand strokes in that file")
  process.exit(1)
}

/** Ramer–Douglas–Peucker — a pen's raw samples are far denser than the eye. */
function simplify(pts, tol) {
  if (pts.length < 3) return pts
  let far = 0
  let max = 0
  const [ax, ay] = pts[0]
  const [bx, by] = pts[pts.length - 1]
  const dx = bx - ax
  const dy = by - ay
  const len = Math.hypot(dx, dy)
  for (let i = 1; i < pts.length - 1; i++) {
    const [px, py] = pts[i]
    const d = len < 1e-9
      ? Math.hypot(px - ax, py - ay)
      : Math.abs(dy * px - dx * py + bx * ay - by * ax) / len
    if (d > max) {
      max = d
      far = i
    }
  }
  if (max <= tol) return [pts[0], pts[pts.length - 1]]
  return [...simplify(pts.slice(0, far + 1), tol).slice(0, -1), ...simplify(pts.slice(far), tol)]
}

/** Matches the freehand branch of basePrims: the user's line, barely roughened. */
const OPTS = {
  roughness: 0.2,
  bowing: 0.35,
  strokeWidth: 1.9,
  disableMultiStroke: true,
  preserveVertices: true,
}

const TOL = 0.35

const minX = Math.min(...strokes.map((n) => n.x))
const minY = Math.min(...strokes.map((n) => n.y))
const maxX = Math.max(...strokes.map((n) => n.x + (n.w ?? 0)))
const maxY = Math.max(...strokes.map((n) => n.y + (n.h ?? 0)))

const gen = rough.generator()
const round = (n) => Math.round(n * 10) / 10
const ds = []
let before = 0
let after = 0

for (const n of strokes) {
  before += n.points.length
  const pts = simplify(n.points, TOL).map(([x, y]) => [n.x - minX + x, n.y - minY + y])
  after += pts.length
  const drawable = gen.linearPath(pts, { ...OPTS, seed: n.seed || 1 })
  for (const p of gen.toPaths(drawable)) {
    if (p.stroke === "none") continue
    ds.push(p.d.replace(/-?\d+(\.\d+)?/g, (m) => String(round(Number(m)))))
  }
}

const w = round(maxX - minX)
const h = round(maxY - minY)

writeFileSync(
  join(root, "lib/sketch/doodle.ts"),
  `// GENERATED by scripts/gen-doodle.mjs — do not edit by hand.\n` +
    `// A drawing made in scrawl, baked to paths for the empty canvas.\n\n` +
    `export const DOODLE_W = ${w}\n` +
    `export const DOODLE_H = ${h}\n\n` +
    `export const DOODLE_PATHS: string[] = [\n` +
    ds.map((d) => `  ${JSON.stringify(d)},`).join("\n") +
    `\n]\n`
)

console.log(`${strokes.length} strokes, ${before} → ${after} points, ${ds.length} paths, ${w}×${h}`)
