// Generates the Phosphor icon data under lib/sketch/ from @phosphor-icons/core.
// Run: node scripts/gen-icons.mjs
//
// Emits two tiers:
//  - phosphor-paths.ts — a curated "regular" subset, inlined in the main bundle
//    so library defs render synchronously with no flash.
//  - phosphor/ — the full catalog: every icon in five weights as lazy chunks,
//    an eager name list (small) and a lazy search index (names + tags).

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { createRequire } from "node:module"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const assetsRoot = join(root, "node_modules/@phosphor-icons/core/assets")

const require = createRequire(import.meta.url)
const { icons: CATALOG } = require("@phosphor-icons/core")

const GENERATED = "// GENERATED by scripts/gen-icons.mjs — do not edit by hand."

// Weights scrawl supports. Duotone is left out: its glyphs carry per-path
// opacity, which the sketch path prim deliberately doesn't have.
const WEIGHTS = ["thin", "light", "regular", "bold", "fill"]

const CURATED = `
user users user-circle user-plus image images magnifying-glass
caret-down caret-right caret-left caret-up caret-up-down check check-circle
x x-circle plus minus list star heart arrow-right arrow-left arrow-up arrow-down
arrow-u-up-left arrow-square-out dots-three dots-three-vertical dots-six-vertical
bell bell-ringing gear house envelope lock lock-open trash upload-simple
download-simple calendar-blank calendar-check info warning warning-circle play
pause squares-four file file-text folder chart-line chart-bar chart-pie
shopping-cart shopping-bag credit-card currency-dollar tag bookmark bookmark-simple
chat-circle chat-teardrop-dots chats-circle paper-plane-tilt sparkle robot
lightning globe link share-network copy pencil-simple pencil-line funnel funnel-simple
sliders-horizontal sort-ascending clock map-pin phone video-camera microphone
paperclip database code terminal browser device-mobile desktop sign-out sign-in
eye eye-slash thumbs-up thumbs-down smiley question shield-check rocket-launch
package truck gift trophy medal fire moon sun palette note notepad kanban
graduation-cap buildings briefcase wallet receipt bank arrows-clockwise
arrows-out arrows-in magic-wand brain cpu plug wrench bug git-branch git-pull-request
cloud cloud-arrow-up wifi-high battery-full camera crop text-aa text-b
list-bullets list-numbers list-checks text-align-left table columns rows
sidebar-simple playlist quotes megaphone hand-waving crown seal-check
lightbulb target flag confetti coins percent hash at squares-four
dot-outline circle square triangle diamond hourglass timer bookmarks
airplane-tilt storefront ticket key fingerprint scan qr-code
`.trim().split(/\s+/)

function pathsOf(name, weight) {
  // non-regular weights carry the weight suffix in the file name
  const file = join(assetsRoot, weight, weight === "regular" ? `${name}.svg` : `${name}-${weight}.svg`)
  if (!existsSync(file)) return null
  const svg = readFileSync(file, "utf8")
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  return ds.length ? ds : null
}

function pathMap(names, weight) {
  const out = {}
  const missing = []
  for (const name of names) {
    const ds = pathsOf(name, weight)
    if (ds) out[name] = ds
    else missing.push(name)
  }
  return { out, missing }
}

function pathMapBody(map) {
  return Object.entries(map)
    .map(([k, v]) => `  ${JSON.stringify(k)}: [${v.map((d) => JSON.stringify(d)).join(", ")}],`)
    .join("\n")
}

// -- curated inline subset (regular) ----------------------------------------

const curated = pathMap([...new Set(CURATED)], "regular")
writeFileSync(
  join(root, "lib/sketch/phosphor-paths.ts"),
  `${GENERATED}\n` +
    `// Phosphor "regular" icons — the curated subset the main bundle carries so\n` +
    `// library defs render with no flash. The full catalog lives in ./phosphor/.\n\n` +
    `export const PHOSPHOR_VB = 256\n\n` +
    `export const PHOSPHOR_PATHS: Record<string, string[]> = {\n${pathMapBody(curated.out)}\n}\n`
)
console.log(`phosphor-paths.ts: ${Object.keys(curated.out).length} curated icons`)
if (curated.missing.length) console.log(`  curated missing (skipped): ${curated.missing.join(" ")}`)

// -- full catalog ------------------------------------------------------------

const genDir = join(root, "lib/sketch/phosphor")
mkdirSync(genDir, { recursive: true })

const allNames = CATALOG.map((i) => i.name).sort()

for (const weight of WEIGHTS) {
  const { out, missing } = pathMap(allNames, weight)
  writeFileSync(
    join(genDir, `catalog-${weight}.ts`),
    `${GENERATED}\n` +
      `// Every Phosphor "${weight}" icon, filled paths in a 0 0 256 256 viewBox.\n` +
      `// Loaded lazily via lib/sketch/icon-catalog.ts — never import directly.\n\n` +
      `export const PATHS: Record<string, string[]> = {\n${pathMapBody(out)}\n}\n`
  )
  console.log(`phosphor/catalog-${weight}.ts: ${Object.keys(out).length} icons`)
  if (missing.length) console.log(`  ${weight} missing (skipped): ${missing.join(" ")}`)
}

// -- eager name list ---------------------------------------------------------

writeFileSync(
  join(genDir, "names.ts"),
  `${GENERATED}\n` +
    `// Every Phosphor icon name — eager and small, so "unknown icon" and\n` +
    `// "still loading" can be told apart synchronously.\n\n` +
    `export const ALL_ICON_NAMES: string[] = ${JSON.stringify(allNames)}\n`
)
console.log(`phosphor/names.ts: ${allNames.length} names`)

// -- lazy search index -------------------------------------------------------

const meta = CATALOG.map((i) => [
  i.name,
  i.tags.filter((t) => t !== "*new*" && t !== "*updated*").join(" "),
  i.categories.join(" "),
])
writeFileSync(
  join(genDir, "meta.ts"),
  `${GENERATED}\n` +
    `// Search index: [name, tags, categories] per icon. Loaded lazily by\n` +
    `// lib/sketch/icon-search.ts alongside the first icon search.\n\n` +
    `export const ICON_META: [string, string, string][] = ${JSON.stringify(meta)}\n`
)
console.log(`phosphor/meta.ts: ${meta.length} entries`)
